# Generated by Django 4.0.4 on 2022-04-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('Key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Value', models.TextField(max_length=5000)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
